parser: babel-eslint
extends:
  - airbnb
  - prettier
  - plugin:prettier/recommended
plugins:
  - prettier
rules:
  import/prefer-default-export: off

settings:
  import/extensions:
    - '.coffee'
    - '.js'
    - '.jsx'
  import/parsers:
    eslint-plugin-coffee/lib/parser:
      - '.coffee'
    babel-eslint:
      - '.js'
      - '.jsx'
  import/resolver:
    node:
      extensions:
        - '.coffee'
        - '.js'
        - '.jsx'
  import/ignore:
    - node_modules
    - "\\.(scss|css|less|hbs|svg|json)$"

overrides:
  - files:
      - '**/*.coffee'
    parser: eslint-plugin-coffee
    plugins:
      - coffee
    settings:
      import/parsers:
        eslint-plugin-coffee/lib/parser:
          - '.coffee'
      babel-eslint:
        - '.js'
        - '.jsx'

    extends:
      - plugin:coffee/airbnb-base
      - plugin:coffee/import
      - plugin:coffee/all
      - plugin:coffee/prettier-run-as-rule

    rules:
      coffee/prefer-destructuring: [error, { object: true }]
      coffee/no-unused-vars: [error, { varsIgnorePattern: ^_+$ }]
      coffee/no-magic-numbers: off
      coffee/vars-on-top: off
      coffee/no-underscore-dangle: off
      coffee/block-scoped-var: off
      max-lines: [warn, 600]
      max-params: [warn, 4]
      max-statements: [warn, 55]
      coffee/max-lines-per-function: [warn, 160]
      coffee/id-length: off
      coffee/no-await-in-loop: off
      coffee/no-return-assign: off
      no-bitwise: 0
      no-continue: 0
      sort-keys: 0
      no-sync: 0
      coffee/multiline-comment-style: off
      coffee/capitalized-comments: off
      no-inline-comments: 0
      no-warning-comments: 0
      line-comment-position: 0
      coffee/implicit-object: error
      coffee/empty-func-parens: [error, 'always']
      coffee/spread-direction: [error, 'prefix']
      handle-callback-err: [error, '^.*(e|E)rr']
      require-atomic-updates: error

env:
  node: true
  es6: true
